version: "3.8"

services:

  front-end:
    restart: unless-stopped
    build :
      context: ./front-end/
      dockerfile: Dockerfile
    container_name: front-end-container
    volumes:
      - ./front-end:/app/front-end
      - /app/front-end/node_modules # Just don`t delete this -_-
    ports: 
      - "3000:3000"

  back-end:
    restart: unless-stopped
    build:
      context: ./back-end/
      dockerfile: Dockerfile
    container_name: back-end-container
    volumes:
      - ./back-end:/app/back-end
      - /app/back-end/node_modules # Just don`t delete this -_-
    ports: 
      - "8000:8000"

  webserver:
    build:
      context: ./webserver/
      dockerfile: Dockerfile
    container_name: webserver-container
    # restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./webserver/config/nginx.conf:/etc/nginx/nginx.conf # Nginx config file
      - ./webserver/logs:/var/log/nginx # Nginx logs
    depends_on:
      - front
      - back
